<manifest
  sharedUserId="android.uid.phone"
  versionCode="0x5"
  versionName="1.1"
  package="com.mediatek.ygps"
  platformBuildVersionCode="24"
  platformBuildVersionName="7.0">
  <uses-sdk
    minSdkVersion="0x10"
    targetSdkVersion="0x17">
  </uses-sdk>
  <uses-permission
    name="android.permission.ACCESS_FINE_LOCATION">
  </uses-permission>
  <uses-permission
    name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS">
  </uses-permission>
  <uses-permission
    name="android.permission.WRITE_EXTERNAL_STORAGE">
  </uses-permission>
  <uses-permission
    name="android.permission.WAKE_LOCK">
  </uses-permission>
  <uses-permission
    name="android.permission.INTERNET">
  </uses-permission>
  <uses-permission
    name="android.permission.ACCESS_NETWORK_STATE">
  </uses-permission>
  <application
    label="YGPS"
    icon="res/drawable/icon.png">
    <activity
      label="YGPS"
      name=".YgpsActivity"
      exported="0xffffffff"
      launchMode="0x3"
      screenOrientation="0x1"
      configChanges="0x3"
      windowSoftInputMode="0x20">
      <intent-filter>
        <action
          name="android.intent.action.MAIN">
        </action>
        <category
          name="android.intent.category.ALTERNATIVE">
        </category>
        <category
          name="android.intent.category.SELECTED_ALTERNATIVE">
        </category>
      </intent-filter>
      <intent-filter>
        <action
          name="android.intent.action.ygps">
        </action>
        <category
          name="android.intent.category.DEFAULT">
        </category>
      </intent-filter>
    </activity>
    <activity
      label="YGPS Copyright Information"
      name=".CopyrightInfo">
    </activity>
    <service
      name=".YgpsService"
      exported="1x1">
    </service>
  </application>
</manifest>
